### ISSUE TITLE
G0 - Responsive image bug

### ISSUE THREAD

**Issue by jpinsent** [ccswbs/hjckrrh#55] opened 2015-06-19 15:02 UTC
Kind of an odd one; if you add the "img-responsive" class and add the style "float: left;" it messes up the page formatting. This can lead to the "File Attachments" text appearing on the same line as the body content.
![responsive image bug 2](https://cloud.githubusercontent.com/assets/12450480/8256108/9c3e82b0-1672-11e5-9712-d013d9e1278d.PNG)

**Comment by brharp** [comment] 2016-06-14 20:14
I'm calling this a duplicate of #16, because it's a consequence of full HTML editing.

**Closed by brharp** 2016-06-14 20:14 UTC
Labels: feature: general (G), priority: low, type: bug
