### ISSUE TITLE
PG0 - Request to add a printing feature to pages

### ISSUE THREAD

**Issue by Samana04** [ccswbs/hjckrrh#397] opened 2016-04-04 15:37 UTC
Client (Student Affairs) has requested the ability to add a printing feature to pages of their website. They would like to be able to print pages with proper formatting.

**Comment by mmafe** [comment] 2016-10-04 17:42
This is a duplicate of https://github.com/ccswbs/hjckrrh/issues/548

**Closed by mmafe** 2016-10-04 17:42 UTC
Labels: feature: page (P), type: client request, type: enhancement request
